@startuml LinkedInScrapper_DiagramaDeClases

BusquedaEgresados --> Configuracion
BusquedaEgresados --> Test
BusquedaEgresados --> Automata
BusquedaEgresados --> Verificador
BusquedaEgresados --> Scrapper
BusquedaEgresados --> Iterador
BusquedaEgresados --> SQL_Links

SQL_Links --> linkEgresadosSQL
SQL_Links --> ConectionDatabase
SQL_Scrapper --> Egresado
SQL_Scrapper --> SQL_Links
SQL_Scrapper --> EgresadosScrapingSQL

ModeloProcesamientoLenguaje --> DatosEgresado
ModeloProcesamientoLenguaje --> SQL_Rol
SQL_Rol --> ConectionDatabase
SQL_Rol --> EgresadosScrapingSQL
SQL_Rol --> EgresadosSQL

ModeloProcesamientoLenguaje --> DataCleaner
ModeloProcesamientoLenguaje --> ImplementadorModelo
ImplementadorModelo --> Tokenizador
ModeloProcesamientoLenguaje --> Tokenizador
Tokenizador --> DataCleaner
DataCleaner --> DatosEgresado

EntrenamientoModelo --> DatosReentreno
EntrenamientoModelo --> DataCleaner
EntrenamientoModelo --> Tokenizador
EntrenamientoModelo --> ReentrenadorModelo

DatosReentreno --> DatosEgresado
DataCleaner --> DatosReentreno
ReentrenadorModelo --> Tokenizador

LinkedInScrapper --> AnalisisController
AnalisisController --> ConexionSQL
ConexionSQL --> baseDatos


baseDatos --> linkEgresadosSQL
baseDatos --> EgresadosScrapingSQL
baseDatos --> EgresadosSQL


class BusquedaEgresados{
    + insertarEnBarraBusqueda()
    + buscarUADY()
    + accederContactosDelPivote()
}

class Iterador{
    + entreElementosDeRespuesta()
    + entrePaginasDeRespuesta()
}

class Configuracion{
    + paginaEnEspanol()
    + buscarContrasenasAlmacenadas()
    + iniciarSesion()
    + cerrarSesion()
}

class Verificador{
    + esUADY()
    + esLIS()
    + tieneExperiencia()
}

class Test{
    + hayInternet()
    + conexionEstable()
    + edgeCaido()
    + linkedinCaido()
}

class Configuracion{
    + paginaEnEspanol()
    + buscarContrasenasAlmacenadas()
    + iniciarSesion()
    + cerrarSesion()
}

class Iterador{
    + entreElementosDeRespuesta()
    + entrePaginasDeRespuesta()
}

class Scrapper{
    - linkPagina
    + obtenerNombre_URL()
}

class SQL_Links{
    + subirLinks()
    + bajarLinks()
}

class Egresado{
    - linkPagina
    - nombreEgresado
    - universidad
    - carrera
    - nombreEmpresa
    - description
}

class SQL_Scrapper{
    + limpiarDuplicado()
    + limpiarMiembroDeLinkedIn()
    + getDatos()
    + setDatos()
    + agregarPivote()
    + eliminarPivote()
}

class Automata{
    + insertarEnBarraBusqueda()
    + buscarUADY()
    + accederContactosDelPivote()
}

class ConectionDatabase{
    + driver 
    + server 
    + database 
    + username 
    + pwd
    + constructor()
    + openConnection()
    + closeConnection()
}

class linkEgresadosSQL{
    + link
}

class EgresadosScrapingSQL{
    + link
    + nombre
    + empresa
    + universidad
    + carrera
    + descripcion
    + duracion
}

class DatosEgresado{
    - nombre
    - empresa
    - rol 
    - descripcion
}

class SQL_Rol{
    + obtenerDatos()
    + subirDatos()
}

class DataCleaner{
    - rawData
    - cleanData
    + eliminarCaracteresEspeciales()
    + convertirMinusculas()
    + eliminarStopWords()
}

class DatosReentreno{
    - descripcion
    - categoria
    +cargarDatos()
}

class ImplementadorModelo{
    - data
    - clasificacion
    + cargarModeloPreentrenado()
    + clasificarDatos()
}

class ReentrenadorModelo{
    - datosDeEntrenamiento
    + configurarModelo()
    + entrenarModelo()
}

class Tokenizador{
    - data 
    - dataTokenizado
    + tokenizarTexto()
}

class EgresadosSQL{
    - nombre
    - empresa
    - rol
}

class baseDatos {
    + analisisEmpresas()
    + analisisRoles()
    + promedioDuracion() 
}

class LinkedInScrapper{
    + pageload()
    + btn_analisis()
}

class AnalisisController{
    + ResultadosEmpresas()
    + ResultadosRoles()
    + ResultadospromedioDuracion()
}

class ConexionSQL{
    + getSingleton()
    + ObtenerConfig()
    + conectar()
    + abrir_conexion()
    + cerrar_conexion()
}

@enduml

