@startuml 

DataCleaner --> DatosEmpleado
DataCleaner --> DatosReentreno
Tokenizador --> DataCleaner
ImplementadorModelo --> Tokenizador
ReentrenadorModelo --> Tokenizador

class DatosEmpleado{
    - nombre
    - empresa
    - rol 
    - descripcion
    + obtenerDatos()
    + subirDatos()
}

class DataCleaner{
    - rawData
    - cleanData
    + eliminarCaracteresEspeciales()
    + convertirMinusculas()
    + eliminarStopWords()
}


class DatosReentreno{
    - descripcion
    - categoria
    +cargarDatos()
}

class ImplementadorModelo{
    - data
    - clasificacion
    + cargarModeloPreentrenado()
    + clasificarDatos()
}


class ReentrenadorModelo{
    - datosDeEntrenamiento
    + configurarModelo()
    + entrenarModelo()
}

class Tokenizador{
    - data 
    - dataTokenizado
    + tokenizarTexto()
}

@enduml